name: CI/CD - Python App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Set up cache for pip
    - name: Get pip cache dir
      run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    #Run application tests
    - name: Application Tests
      run: |
        export PYTHONPATH=src
        python tests/test_application.py

    # Install AWS CLI v2 & EB
    - name: Check AWS CLI Version
      run: aws --version

    - name: Install or Update EB CLI
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade awsebcli
        eb --version

    # AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    # Create the Elastic Beanstalk application
    - name: Deploy to AWS Elastic Beanstalk
      run: |
        if eb list | grep -q "test-environment"; then
          echo "Environment exists, deploying..."
          eb use test-environment
          eb status test-environment
          eb deploy
        else
          echo "Environment does not exist, creating..."
          eb init -p python-3.8 eb-app --region eu-west-3  # Initialize the project
          eb create test-environment --cname test-env-art --timeout 15
        fi
